### ISSUE TITLE
Factoring in revenue

### ISSUE THREAD

**Issue by ucjonathan** [sendwithus/confidence#10]
Is it possible to us this library to calculate a winner in an A/B test where the variations have different price points?

So for example we could have two variations:

Variation A - 112 views / 31 conversions / 4.95 revenue per conversion = total revenue $153.45 / Average Revenue Per Visitor = $1.37
Variation B - 102 views / 24 conversions / 5.95 revenue per conversion = total revenue $142.80 / Average Revenue Per Visitor = $1.40

How would we determine with 95% or 99% confidence that Variation B is better than Variation A?

**Comment by demoore** [comment]
Views and conversions (well, events and conversions) are only supported. I'd be happy to look at a PR if you want to fork and extend it.
